---
    - name: Install required system packages
      apt:
        update_cache: yes
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Work out the distribution
      command: lsb_release -cs
      register: release

    - name: Get architecture
      shell: dpkg --print-architecture
      register: deb_architecture

    - name: Add Docker Repository
      apt_repository:
        repo: "deb [arch={{deb_architecture.stdout}}] https://download.docker.com/linux/debian {{ release.stdout }} stable"
        state: present
        update_cache: yes

    - name: Install docker-ce
      apt:
        force: True
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
      notify:
        - restart docker

    - name: Install Docker Module for Python
      pip:
        name: docker
