---
#    vars:
#      - os_agent_arch

#    - name: Install required system packages
#      apt:
#        update_cache: yes
#        pkg:
#          - network-manager
#          - jq
#          - wget
#          - curl
#          - udisks2
#          - libglib2.0-bin
#          - dbus
#          - net-tools

    - name: Create a directory downloads
      ansible.builtin.file:
        path: /srv/downloads
        state: directory
        mode: '0750'




#os-agent_1.2.2_linux_armv7.deb
    - name: Get architecture
      shell: dpkg --print-architecture
      register: deb_architecture

#    - name: set default os_agent_arch
#      set_fact: os_agent_arch = {{ deb_architecture.stdout }}
    - name: set default os_agent_arch
      set_fact:
        os_agent_arch: "{{ deb_architecture.stdout }}"

    - name: set os_agent_arch to armv7
      set_fact:
        os_agent_arch: armv7
      when: deb_architecture.stdout == "armhf"


    - name: Download os-agent
      get_url:
        url: "https://github.com/home-assistant/os-agent/releases/download/1.2.2/os-agent_1.2.2_linux_{{os_agent_arch}}.deb"
        dest: /srv/downloads/os-agent.deb
        mode: '0440'
        force: no


    - name: Install os-agent
      apt:
        deb: /srv/downloads/os-agent.deb

    - name: Download homeassistant-supervised.deb
      get_url:
        url: https://github.com/home-assistant/supervised-installer/releases/latest/download/homeassistant-supervised.deb
        dest: /srv/downloads/homeassistant-supervised.deb
        mode: '0440'
        force: no

    - name: Install homeassistant
      apt:
        deb: /srv/downloads/homeassistant-supervised.deb

    - name: Download hucs
      get_url:
        url: https://get.hacs.xyz
        dest: /srv/downloads/hucs-install.sh
        mode: '0755'
        force: no
